### ISSUE TITLE
Unable to install Reddit and missing Twitter icon

### ISSUE THREAD

**Issue by LIlaUraraka** [filips123/FirefoxPWA#71]
I was trying to install Reddit, but I keep getting this error, Twitter also is missing it's icon: 

> Failed to parse PWA manifest: Provided URL (https://www.redditstatic.com/) is not within the scope (https://www.reddit.com/)

> https://imgur.com/a/vYDmM9h

**Comment by filips123** [comment]
**Reddit:**

Reddit's manifest is broken and does not follow the specification (see #61 for more details). Unfortunately, there is nothing I can do about this, but you can uncheck "Use the manifest for determining app properties" when installing Reddit and it should install fine.

**Twitter:**

It seems Twitter recently decided not to send a complete manifest to clients that don't set a user-agent header, and FirefoxPWA is one of the clients that does not send user-agent headers (because nothing is set by default). And that "limited" manifest FirefoxPWA will receive does not contain icons. I don't know why Twitter decided to do this.
I will set some known user-agent in the next release to prevent such problems. But you can currently also uncheck "Use the manifest for determining app properties" here to get the correct icon.

*Manifest when user-agent header is empty (what FirefoxPWA receives):*

```json
{
  "name": "Twitter",
  "short_name": "Twitter",
  "start_url": "/?utm_source=web_app_manifest",
  "display": "standalone",
  "gcm_sender_id": "49625052041",
  "gcm_user_visible_only": true,
  "prefer_related_applications": true,
  "related_applications": [
    {
      "platform": "play",
      "id": "com.twitter.android"
    }
  ]
}
```

*Manifest when user-agent header is set (what it should receive):*

```json
{
  "background_color": "#ffffff",
  "categories": [
    "social",
    "news",
    "magazines"
  ],
  "description": "Get breaking news, politics, trending music, world events, sports scores and the latest global news stories as they unfold – all with less data.",
  "display": "standalone",
  "gcm_sender_id": "49625052041",
  "gcm_user_visible_only": true,
  "icons": [
    {
      "src": "https://abs.twimg.com/responsive-web/client-web/icon-default.ee534d85.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "https://abs.twimg.com/responsive-web/client-web/icon-default-large.8e027b65.png",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "purpose": "maskable",
      "src": "https://abs.twimg.com/responsive-web/client-web/icon-default-maskable.2fd29c85.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "purpose": "maskable",
      "src": "https://abs.twimg.com/responsive-web/client-web/icon-default-maskable-large.ee2b7aa5.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "name": "Twitter",
  "screenshots": [
    {
      "src": "https://abs.twimg.com/responsive-web/client-web/twitter-lite-data-saver-marketing.9343a915.png",
      "sizes": "586x1041",
      "type": "image/png"
    },
    {
      "src": "https://abs.twimg.com/responsive-web/client-web/twitter-lite-explore-marketing.f1a09635.png",
      "sizes": "586x1041",
      "type": "image/png"
    },
    {
      "src": "https://abs.twimg.com/responsive-web/client-web/twitter-lite-timeline-marketing.ff3ea885.png",
      "sizes": "586x1041",
      "type": "image/png"
    }
  ],
  "share_target": {
    "action": "compose/tweet",
    "enctype": "multipart/form-data",
    "method": "POST",
    "params": {
      "title": "title",
      "text": "text",
      "url": "url",
      "files": [
        {
          "name": "externalMedia",
          "accept": [
            "image/jpeg",
            "image/png",
            "image/gif",
            "video/quicktime",
            "video/mp4"
          ]
        }
      ]
    }
  },
  "shortcuts": [
    {
      "name": "New Tweet",
      "url": "/compose/tweet?utm_source=jumplist&utm_medium=shortcut",
      "icons": [
        {
          "src": "https://abs.twimg.com/responsive-web/client-web/icon-compose.12384425.png",
          "type": "image/png",
          "sizes": "192x192"
        }
      ]
    },
    {
      "name": "Explore",
      "url": "/explore?utm_source=jumplist&utm_medium=shortcut",
      "icons": [
        {
          "src": "https://abs.twimg.com/responsive-web/client-web/icon-search-stroke.5f9aa885.png",
          "type": "image/png",
          "sizes": "192x192"
        }
      ]
    },
    {
      "name": "Notifications",
      "url": "/notifications?utm_source=jumplist&utm_medium=shortcut",
      "icons": [
        {
          "src": "https://abs.twimg.com/responsive-web/client-web/icon-notifications-stroke.429602d5.png",
          "type": "image/png",
          "sizes": "192x192"
        }
      ]
    },
    {
      "name": "Direct Messages",
      "url": "/messages?utm_source=jumplist&utm_medium=shortcut",
      "icons": [
        {
          "src": "https://abs.twimg.com/responsive-web/client-web/icon-messages-stroke.5f95edc5.png",
          "type": "image/png",
          "sizes": "192x192"
        }
      ]
    }
  ],
  "short_name": "Twitter",
  "start_url": "https://twitter.com/?utm_source=homescreen&utm_medium=shortcut",
  "theme_color": "#ffffff",
  "scope": "/",
  "android_package_name": "com.twitter.android",
  "prefer_related_applications": true,
  "related_applications": [
    {
      "id": "com.twitter.android",
      "platform": "chromeos_play",
      "url": "https://play.google.com/store/apps/details?id=com.twitter.android"
    }
  ]
}
```

**Comment by filips123** [comment]
This has been fixed in [v1.2.2](https://github.com/filips123/FirefoxPWA/releases/tag/v1.2.2).

**Comment by isle9** [comment]
Still doesn't work on Reddit unless you uncheck "Use the manifest for determining app properties".

**Comment by filips123** [comment]
Because Reddit still doesn't follow the specification and provides an invalid manifest...

Yes, maybe my parser should be less strict and just ignore elements with errors, and I may revisit this in the future. But really, this is something that Reddit should fix.
